services:

  postgres:
    image: pgvector/pgvector:pg16

  backend:
    image: sanju0123/multimodal-backend:latest
    env_file:
      - .env

  frontend:
    image: sanju0123/multimodal-frontend:latest
